/**
 * Gets a random image from the public/unsplash folder and subfolders
 * 
 * This function uses a pre-generated list of images. To regenerate the list,
 * run the build script: npm run generate:images
 * 
 * @returns A path to a random image (e.g., "/flygare-design/unsplash/bmBLu_oAEj8.jpg")
 */
export function getRandomPlaceholderImage(): string {
  const images = getAllPlaceholderImages();
  if (images.length === 0) return 'https://placehold.co/400x600';
  const randomIndex = Math.floor(Math.random() * images.length);
  return images[randomIndex];
}

/**
 * Returns a stable image for a given ID string.
 * Same ID always returns the same image — no flickering on re-render.
 */
export function getPlaceholderImage(id: string): string {
  const images = getAllPlaceholderImages();
  if (images.length === 0) return 'https://placehold.co/400x600';
  let hash = 0;
  for (let i = 0; i < id.length; i++) {
    hash = ((hash << 5) - hash + id.charCodeAt(i)) | 0;
  }
  return images[Math.abs(hash) % images.length];
}

/**
 * Gets all available placeholder images from the unsplash folder
 * @returns Array of all image paths
 */
export function getAllPlaceholderImages(): string[] {
  const baseUrl = import.meta.env.BASE_URL || "/";
  const normalizedBaseUrl = baseUrl.endsWith("/") ? baseUrl : `${baseUrl}/`;

  // This list is auto-generated by scanning the public/unsplash directory
  // To regenerate, run: npm run generate:images
  return [
    `${normalizedBaseUrl}unsplash/-aWq1gLxnOk.jpg`,
    `${normalizedBaseUrl}unsplash/-nte12rkTok.jpg`,
    `${normalizedBaseUrl}unsplash/03g3xzFQqvo.jpg`,
    `${normalizedBaseUrl}unsplash/0s81Kf6lWzY.jpg`,
    `${normalizedBaseUrl}unsplash/15I0MTCuN4c.jpg`,
    `${normalizedBaseUrl}unsplash/6kBBOAZpdd4.jpg`,
    `${normalizedBaseUrl}unsplash/7Dj4W7p0nFg.jpg`,
    `${normalizedBaseUrl}unsplash/7EbTsj8Yuck.jpg`,
    `${normalizedBaseUrl}unsplash/7RUIGJ9doDo.jpg`,
    `${normalizedBaseUrl}unsplash/8mYncdaPc98.jpg`,
    `${normalizedBaseUrl}unsplash/AIbMJrq-C-E.jpg`,
    `${normalizedBaseUrl}unsplash/AQQHJSLdwqY.jpg`,
    `${normalizedBaseUrl}unsplash/AVv_dVCQ5k8.jpg`,
    `${normalizedBaseUrl}unsplash/AviKHQqXX4c.jpg`,
    `${normalizedBaseUrl}unsplash/BUIs-1ihoCA.jpg`,
    `${normalizedBaseUrl}unsplash/BWJNI_g8FLw.jpg`,
    `${normalizedBaseUrl}unsplash/Bdx-lKuxkK4.jpg`,
    `${normalizedBaseUrl}unsplash/DbP__bYyGdM.jpg`,
    `${normalizedBaseUrl}unsplash/E7C077ex-Zk.jpg`,
    `${normalizedBaseUrl}unsplash/EJFabiZWAiQ.jpg`,
    `${normalizedBaseUrl}unsplash/ER7MHUngu_0.jpg`,
    `${normalizedBaseUrl}unsplash/Ejlj69BGyoE.jpg`,
    `${normalizedBaseUrl}unsplash/EvHdiHCZfEA.jpg`,
    `${normalizedBaseUrl}unsplash/F8ccXuGnflg.jpg`,
    `${normalizedBaseUrl}unsplash/G8dAAP0IrRk.jpg`,
    `${normalizedBaseUrl}unsplash/GCINwY2-j9M.jpg`,
    `${normalizedBaseUrl}unsplash/GPBeiGsbZ_4.jpg`,
    `${normalizedBaseUrl}unsplash/GtXf3-QWclI.jpg`,
    `${normalizedBaseUrl}unsplash/HBAhBZryJSs.jpg`,
    `${normalizedBaseUrl}unsplash/I4W8z_zMRlE.jpg`,
    `${normalizedBaseUrl}unsplash/KE_ksBiNgdg.jpg`,
    `${normalizedBaseUrl}unsplash/Korz-XGIRnc.jpg`,
    `${normalizedBaseUrl}unsplash/KzQI2NP2apY.jpg`,
    `${normalizedBaseUrl}unsplash/NHEV2Vhv_uU.jpg`,
    `${normalizedBaseUrl}unsplash/Nxn8Nm2yx0I.jpg`,
    `${normalizedBaseUrl}unsplash/PtnZ24-yXdU.jpg`,
    `${normalizedBaseUrl}unsplash/PxEp-wgS00w.jpg`,
    `${normalizedBaseUrl}unsplash/R4679uf28lY.jpg`,
    `${normalizedBaseUrl}unsplash/R86bzJSneuw.jpg`,
    `${normalizedBaseUrl}unsplash/SYPJnLEp3Go.jpg`,
    `${normalizedBaseUrl}unsplash/TSon9oPf0fo.jpg`,
    `${normalizedBaseUrl}unsplash/VAbY0VfBcCI.jpg`,
    `${normalizedBaseUrl}unsplash/WRncbwcYH3U.jpg`,
    `${normalizedBaseUrl}unsplash/XzPwFw8W6FQ.jpg`,
    `${normalizedBaseUrl}unsplash/YlJaYg1qb9w.jpg`,
    `${normalizedBaseUrl}unsplash/_uP1NW_gbBU.jpg`,
    `${normalizedBaseUrl}unsplash/bmBLu_oAEj8.jpg`,
    `${normalizedBaseUrl}unsplash/d-V9Hj9xn3M.jpg`,
    `${normalizedBaseUrl}unsplash/dAj9D3q7kT0.jpg`,
    `${normalizedBaseUrl}unsplash/dINil0ZRcNs.jpg`,
    `${normalizedBaseUrl}unsplash/dXS-WsoYP5U.jpg`,
    `${normalizedBaseUrl}unsplash/g-EHLcgpVqQ.jpg`,
    `${normalizedBaseUrl}unsplash/gi7zy34qvXA.jpg`,
    `${normalizedBaseUrl}unsplash/hOh0XyrS_k0.jpg`,
    `${normalizedBaseUrl}unsplash/ihMWAYLpzI8.jpg`,
    `${normalizedBaseUrl}unsplash/jTP3p3tAF-E.jpg`,
    `${normalizedBaseUrl}unsplash/jX61Kll0Q5g.jpg`,
    `${normalizedBaseUrl}unsplash/j_XBD_c7i40.jpg`,
    `${normalizedBaseUrl}unsplash/kQu71SCrwns.jpg`,
    `${normalizedBaseUrl}unsplash/kTk6HW3ywRg.jpg`,
    `${normalizedBaseUrl}unsplash/lx3zjfLpSr4.jpg`,
    `${normalizedBaseUrl}unsplash/mco85YE-6ac.jpg`,
    `${normalizedBaseUrl}unsplash/mdkmFNuXH38.jpg`,
    `${normalizedBaseUrl}unsplash/nx9eAX7eC3w.jpg`,
    `${normalizedBaseUrl}unsplash/o2cZ37sR0u0.jpg`,
    `${normalizedBaseUrl}unsplash/pL2dx4xrSKI.jpg`,
    `${normalizedBaseUrl}unsplash/q6JIzDQaJ9o.jpg`,
    `${normalizedBaseUrl}unsplash/rPR3JkUAn5M.jpg`,
    `${normalizedBaseUrl}unsplash/sAMBxQHUfB0.jpg`,
    `${normalizedBaseUrl}unsplash/sJbuC8T0yOw.jpg`,
    `${normalizedBaseUrl}unsplash/tkrbKM0r_Rs.jpg`,
    `${normalizedBaseUrl}unsplash/tqXOn8lw-kc.jpg`,
    `${normalizedBaseUrl}unsplash/u53KxQTUuIA.jpg`,
    `${normalizedBaseUrl}unsplash/uQaXNlWfzuY.jpg`,
    `${normalizedBaseUrl}unsplash/vGpp3A4vOz0.jpg`,
    `${normalizedBaseUrl}unsplash/wKOErkcAjLo.jpg`,
    `${normalizedBaseUrl}unsplash/xg2R3X6L13U.jpg`,
    `${normalizedBaseUrl}unsplash/yHuTF8GctwA.jpg`,
    `${normalizedBaseUrl}unsplash/ywJVYGIgZw4.jpg`,
    `${normalizedBaseUrl}unsplash/zcxr2cdQnig.jpg`,
  ];
}
